# Form implementation generated from reading ui file 'listItem.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(534, 43)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_id = QtWidgets.QLabel(parent=Form)
        self.label_id.setObjectName("label_id")
        self.horizontalLayout.addWidget(self.label_id)
        self.label_name = QtWidgets.QLabel(parent=Form)
        self.label_name.setObjectName("label_name")
        self.horizontalLayout.addWidget(self.label_name)
        self.label_username = QtWidgets.QLabel(parent=Form)
        self.label_username.setObjectName("label_username")
        self.horizontalLayout.addWidget(self.label_username)
        self.label_email = QtWidgets.QLabel(parent=Form)
        self.label_email.setObjectName("label_email")
        self.horizontalLayout.addWidget(self.label_email)
        self.btn_remove = QtWidgets.QPushButton(parent=Form)
        self.btn_remove.setObjectName("btn_remove")
        self.horizontalLayout.addWidget(self.btn_remove)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_id.setText(_translate("Form", "id"))
        self.label_name.setText(_translate("Form", "name"))
        self.label_username.setText(_translate("Form", "username"))
        self.label_email.setText(_translate("Form", "email"))
        self.btn_remove.setText(_translate("Form", "remove"))
